GET http://localhost:8080/demo?likes=Teaching&age=19
Authorization: Basic srini srini

###
GET http://localhost:8080/demo
Authorization: Basic srini srini

###
GET http://localhost:8080/demo?age=18
Authorization: Basic demo demo

###
GET http://localhost:8080/trigger-alert
#Authorization: Basic srini srini

###
GET http://localhost:8080/api/v1/accounts
